// English Reviews
const enReviews = [
    { id: 1, reviewerName: "Michael R.", age: "48", location: "Dallas, TX", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face", rating: 5, content: "I had been struggling with ED for three years. It was killing my marriage and my self-esteem. I was too embarrassed to talk to my regular doctor, so I kept putting it off. Then a buddy mentioned Sarah. Man, I'm so glad I reached out. She didn't make me feel awkward at all - just listened and asked the right questions. She set me up with Viagra and explained exactly how to use it. First time I tried it, I felt like my old self again. My wife and I are closer than we've been in years. Sarah checks in on me regularly too, which means a lot.", date: "03/15/2025", effect: "Complete Recovery", usageTime: "3 months with Sarah", featured: true },
    { id: 2, reviewerName: "James T.", age: "52", location: "Atlanta, GA", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face", rating: 5, content: "I'll be honest - I was skeptical about reaching out to someone online. But I was desperate. My relationship with my girlfriend was on the rocks because I couldn't perform. Sarah was incredibly patient. She didn't push anything on me, just explained my options. We started with half a dose to see how my body reacted. No side effects, and the results were amazing. My confidence is through the roof now. I'm actually dating again, feeling like I'm in my 30s.", date: "03/22/2025", effect: "Major Improvement", usageTime: "2 months with Sarah", featured: true },
    { id: 3, reviewerName: "David K.", age: "45", location: "Phoenix, AZ", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face", rating: 5, content: "The thing about ED that nobody talks about is how it messes with your head. I was avoiding intimacy, making excuses, feeling like less of a man. My wife thought I wasn't attracted to her anymore. Sarah understood all of that. She recommended Cialis because I told her I didn't want to 'plan' everything. Now I just take it Friday evening and I'm good for the whole weekend. Feels natural, not forced. Sarah really gets it.", date: "04/08/2025", effect: "Complete Recovery", usageTime: "4 months with Sarah", featured: true },
    { id: 4, reviewerName: "Robert M.", age: "50", location: "Denver, CO", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face", rating: 5, content: "I'm a pretty frugal guy, so I was worried about the cost. Sarah actually listened to my budget concerns and suggested a generic option that was way more affordable than I expected. She explained the differences, the pros and cons, never pressured me into the expensive stuff. I've been using it for two months now and honestly, I can't tell the difference from the brand name stuff I tried before. Sarah treats you like a person, not a paycheck.", date: "04/17/2025", effect: "Significant Improvement", usageTime: "2 months with Sarah", featured: true },
    { id: 5, reviewerName: "Chris B.", age: "38", location: "Miami, FL", avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop&crop=face", rating: 5, content: "I had two problems - couldn't get hard AND couldn't last. I was thinking I'd need two different medications. Sarah suggested this dual-action pill instead. Let me tell you, this stuff is incredible. I went from barely 2 minutes to lasting 20+ minutes, and I'm rock solid the whole time. My girlfriend's reaction the first time... priceless. She literally said 'what happened to you?' Sarah saved me money AND fixed both issues at once.", date: "05/03/2025", effect: "Complete Recovery", usageTime: "2 months with Sarah", featured: true },
    { id: 6, reviewerName: "Jason P.", age: "42", location: "Seattle, WA", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face", rating: 5, content: "A friend recommended Sarah after I complained about my 'performance issues' during a fishing trip. I was embarrassed even talking to him, but he swore by her. Best decision I made. Sarah asked detailed questions about my lifestyle, my health, even my diet. She didn't just throw pills at me - she actually created a plan. The follow-up care is what surprised me most. She actually remembers our conversations and adjusts things based on how I'm doing.", date: "05/19/2025", effect: "Major Results", usageTime: "3 months with Sarah", featured: true },
    { id: 7, reviewerName: "William H.", age: "60", location: "Chicago, IL", avatar: "https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=100&h=100&fit=crop&crop=face", rating: 5, content: "Divorced for 5 years, finally met someone special. The thought of disappointing her terrified me. I almost called off our relationship before it started. Sarah was so understanding - she didn't treat me like an old man, just a guy who needed help. She was careful about my health history, made sure my heart was good before prescribing anything. First time with my new lady... everything worked perfectly. We're talking about moving in together now. Sarah gave me my second chance at love.", date: "06/02/2025", effect: "Complete Recovery", usageTime: "4 months with Sarah", featured: true },
    { id: 8, reviewerName: "Thomas S.", age: "55", location: "Boston, MA", avatar: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=100&h=100&fit=crop&crop=face", rating: 5, content: "Type 2 diabetic here. I'd been told ED was just something I had to live with. My wife had basically accepted that part of our marriage was over. Sarah was different - she asked about my diabetes, my medications, even sent me for a heart check before we started. She was cautious and thorough. Now? Let's just say my wife is very happy, and so am I. Sarah knows her stuff and actually cares about your safety.", date: "06/14/2025", effect: "Significant Improvement", usageTime: "3 months with Sarah", featured: true },
    { id: 9, reviewerName: "Daniel L.", age: "47", location: "Portland, OR", avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=100&h=100&fit=crop&crop=face", rating: 5, content: "20 years of marriage, and things had gotten... routine. Then they stopped working entirely. The pressure was crushing me. Sarah didn't try to sell me the most expensive stuff. She actually recommended something affordable and appropriate for my situation. Two months in, my wife and I are like newlyweds again. Sarah even gave me tips on overall health - diet, exercise, stress management. She treats the whole person.", date: "06/28/2025", effect: "Complete Recovery", usageTime: "2 months with Sarah", featured: true },
    { id: 10, reviewerName: "Matthew C.", age: "35", location: "Austin, TX", avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&h=100&fit=crop&crop=face", rating: 5, content: "Startup life destroyed my health - 80-hour weeks, constant stress, terrible diet. By 35, I had the sex drive of a 70-year-old. My girlfriend was understanding, but I knew it was killing our relationship. Sarah created a whole wellness plan, not just meds. She checks in to make sure I'm sleeping better, managing stress. The change has been incredible - in bed AND in my energy levels at work. I'm evangelizing about Sarah to all my founder friends.", date: "07/11/2025", effect: "Complete Recovery", usageTime: "3 months with Sarah", featured: true },
    { id: 11, reviewerName: "Anthony G.", age: "43", location: "Las Vegas, NV", avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&h=100&fit=crop&crop=face", rating: 5, content: "First time ever consulting about this stuff online. I was awkward as hell, stumbling over my words. Sarah made it comfortable. She has this way of talking about everything matter-of-factly, no judgment. She explained dosage timing, what to expect, what to avoid. I've been using her recommendations for two months now, and every single time has been successful. My confidence is back, and I'm actually enjoying dating again.", date: "07/24/2025", effect: "Major Improvement", usageTime: "2 months with Sarah", featured: false },
    { id: 12, reviewerName: "Kevin W.", age: "49", location: "San Diego, CA", avatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=100&h=100&fit=crop&crop=face", rating: 5, content: "I'd tried ordering stuff online before - sketchy websites, questionable pills, inconsistent results. Sarah was completely different. Professional, licensed, actually knew what she was talking about. She switched me to a different medication that works better for my body, adjusted the timing, and now it's smooth sailing every time. The difference between some random internet pharmacy and an actual medical professional is huge.", date: "08/05/2025", effect: "Excellent Results", usageTime: "1 month with Sarah", featured: false },
    { id: 13, reviewerName: "Brian N.", age: "40", location: "New York, NY", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face", rating: 5, content: "My girlfriend was getting frustrated with our sex life - or lack thereof. I was avoiding intimacy, making excuses about being tired. The truth was I couldn't perform and didn't know what to do. Sarah was reassuring. She said this was fixable, gave me a specific plan. First time after starting treatment, I lasted 15 minutes. My girlfriend was shocked - in a good way. Our relationship is stronger than ever. Sarah literally saved us.", date: "08/18/2025", effect: "Complete Recovery", usageTime: "2 months with Sarah", featured: true },
    { id: 14, reviewerName: "Steven D.", age: "58", location: "Nashville, TN", avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100&h=100&fit=crop&crop=face", rating: 5, content: "Thought my sex life was over at my age. My son actually convinced me to contact Sarah - he was worried about me being alone. Sarah explained how the medicine works, that age isn't the barrier I thought it was. She was respectful, never made me feel old or embarrassed. Now I'm dating again, keeping up with women 10 years younger than me. Feels incredible to have that part of my life back. Thanks to Sarah and my son's push.", date: "09/01/2025", effect: "Significant Improvement", usageTime: "4 months with Sarah", featured: true },
    { id: 15, reviewerName: "Mark F.", age: "46", location: "Houston, TX", avatar: "https://images.unsplash.com/photo-1542596594-649edbc13630?w=100&h=100&fit=crop&crop=face", rating: 5, content: "I'm a truck driver, on the road constantly. Regular meds were hard to time right with my crazy schedule. Sarah understood my lifestyle immediately. She recommended something longer-lasting so I didn't have to plan everything precisely. Works perfectly for my unpredictable schedule. She even texts me reminders when she knows I'm on a long haul. That's the kind of personal attention you don't expect.", date: "09/14/2025", effect: "Working Great", usageTime: "3 months with Sarah", featured: false },
    { id: 16, reviewerName: "Eric J.", age: "37", location: "Los Angeles, CA", avatar: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=100&h=100&fit=crop&crop=face", rating: 5, content: "Newly married and already having problems in the bedroom. The pressure was intense - new wife, expectations, plus my own anxiety. Sarah was quick to respond, understood the urgency of my situation. First time using her recommendations was our honeymoon all over again. Six months later, we're still going strong. I credit Sarah with giving my marriage the start it deserved.", date: "09/27/2025", effect: "Complete Recovery", usageTime: "6 months with Sarah", featured: true },
    { id: 17, reviewerName: "Ryan P.", age: "51", location: "Philadelphia, PA", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face", rating: 5, content: "High blood pressure and ED is a scary combination. I'd been afraid to try anything because of my heart. Sarah took the time to review ALL my medications, consulted with me about timing and safety. She was more thorough than my own doctor. Three months in, my blood pressure is stable AND my ED is handled. She coordinated with my cardiologist to make sure everything was safe. That's real professionalism.", date: "10/08/2025", effect: "Significant Improvement", usageTime: "3 months with Sarah", featured: false },
    { id: 18, reviewerName: "Jeffrey A.", age: "44", location: "Charlotte, NC", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face", rating: 5, content: "Second marriage, and I was terrified of screwing it up. My first marriage ended partly because of intimacy issues I never addressed. Didn't want to repeat that pattern. Sarah did a full consultation, recommended exactly what I needed. My new wife has no idea I ever had a problem - she thinks I'm just naturally this way. Sarah's discretion and effectiveness gave me a fresh start.", date: "10/22/2025", effect: "Complete Recovery", usageTime: "2 months with Sarah", featured: true },
    { id: 19, reviewerName: "Andrew S.", age: "41", location: "Detroit, MI", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face", rating: 5, content: "I'd tried pills before, supplements, even those sketchy online remedies. Nothing worked. I was ready to give up, accept this was my life now. Sarah was my last try. She explained why those other things failed and how her approach was different. She was right. For the first time in years, everything works like it should. I'm telling every guy I know who's struggling - call Sarah.", date: "11/04/2025", effect: "Complete Recovery", usageTime: "4 months with Sarah", featured: true },
    { id: 20, reviewerName: "Timothy R.", age: "56", location: "San Francisco, CA", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face", rating: 5, content: "Prostate surgery at 54 left me with ED. My urologist said it might improve, might not. It didn't. I was depressed, felt like half a man. Sarah connected with my surgeon to understand my specific situation, then created a careful, gradual treatment plan. Started low and slow. Now, two years post-surgery, my wife and I are intimate again. It's different than before, but it's good. Sarah never gave up on me when I was ready to give up on myself.", date: "11/17/2025", effect: "Significant Improvement", usageTime: "5 months with Sarah", featured: true }
];

// Arabic Reviews
const arReviews = [
    { id: 1, reviewerName: "أحمد الفهد", age: "48", location: "الرياض، السعودية", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face", rating: 5, content: "عانيت من ضعف الانتصاب لمدة ثلاث سنوات. كان يدمر زواجي وثقتي بنفسي. كنت أشعر بالخجل الشديد من التحدث مع طبيبي المعتاد، فكنت أؤجل الموضوع دائماً. ثم ذكر لي صديق اسم سارة. والله يا رجل، أنا سعيد جداً أنني تواصلت معها. لم تجعلني أشعر بالإحراج أبداً - فقط استمعت وسألت الأسئلة الصحيحة. وضعت لي خطة علاج وشرحت لي بالضبط كيفية استخدامها. في المرة الأولى جربتها، شعرت أنني عدت لذاتي مرة أخرى. أنا وزوجتي أصبحنا أقرب مما كنا عليه منذ سنوات. سارة تتابعني باستمرار أيضاً، وهذا يعني الكثير.", date: "15/03/2025", effect: "شفاء تام", usageTime: "3 أشهر مع سارة", featured: true },
    { id: 2, reviewerName: "محمد العلي", age: "52", location: "دبي، الإمارات", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face", rating: 5, content: "سأكون صريحاً - كنت متشككاً في التواصل مع شخص عبر الإنترنت. لكنني كنت يائساً. علاقتي مع خطيبتي كانت على وشك الانتهاء لأنني لم أكن أستطيع الأداء. كانت سارة صبورة بشكل لا يصدق. لم تضغط علي بأي شيء، فقط شرحت لي الخيارات المتاحة. بدأنا بنصف جرعة لنرى كيف يتفاعل جسمي. لم يكن هناك آثار جانبية، وكانت النتائج مذهلة. ثقتي في ذاتي الآن في أعلى مستوياتها. أشعر وكأنني في الثلاثينيات من عمري.", date: "22/03/2025", effect: "تحسن كبير", usageTime: "شهران مع سارة", featured: true },
    { id: 3, reviewerName: "خالد السيد", age: "45", location: "القاهرة، مصر", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face", rating: 5, content: "الشيء في ضعف الانتصاب الذي لا يتحدث عنه أحد هو كيف يؤثر على عقلك. كنت أتجنب الحميمية وأختلق الأعذار وأشعر أنني رجل أقل. زوجتي ظنت أنني لم أعد أشعر بالجاذبية لها. سارة فهمت كل ذلك. أوصتني بعلاج مناسب لأنني قلت لها إنني لا أريد التخطيط لكل شيء. الآن أتناوله مساء الجمعة وأكون جاهزاً طوال عطلة نهاية الأسبوع. يشعر طبيعياً، غير مفتعل. سارة حقاً تفهم.", date: "08/04/2025", effect: "شفاء تام", usageTime: "4 أشهر مع سارة", featured: true },
    { id: 4, reviewerName: "عمر الحسن", age: "50", location: "الدوحة، قطر", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face", rating: 5, content: "أنا رجل مقتصد، لذا كنت قلقاً من التكلفة. سارة استمعت فعلاً لمخاوفي المالية واقترحت عليّ خياراً عاماً كان أرخص بكثير مما توقعت. شرحت لي الفروقات والإيجابيات والسلبيات، ولم تضغط عليّ أبداً لشراء الأدوية الباهظة. استخدمته الآن لمدة شهرين وصراحة، لا أشعر بأي فرق عن الأدوية الأصلية التي جربتها من قبل. سارة تعاملك كإنسان، وليس كمصدر دخل.", date: "17/04/2025", effect: "تحسن ملحوظ", usageTime: "شهران مع سارة", featured: true },
    { id: 5, reviewerName: "يوسف إبراهيم", age: "38", location: "الكويت", avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop&crop=face", rating: 5, content: "كان لدي مشكلتان - لم أستطع الانتصاب ولم أستطع التحمل. اعتقدت أنني سأحتاج إلى دواءين مختلفين. اقترحت سارة عليّ بديلاً ثنائي المفعول. دعني أخبرك، هذا الشيء لا يصدق. انتقلت من دقيقتين إلى أكثر من 20 دقيقة، وأكون صلباً طوال الوقت. رد فعل خطيبتي في المرة الأولى... لا يُقدر بثمن. قالت حرفياً 'ماذا حدث لك؟' سارة وفرت لي المال وحلت المشكلتين معاً.", date: "03/05/2025", effect: "شفاء تام", usageTime: "شهران مع سارة", featured: true },
    { id: 6, reviewerName: "عبدالله الرashid", age: "42", location: "عمان، الأردن", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face", rating: 5, content: "أوصاني صديق بسارة بعد أن شكوت له من 'مشاكل الأداء' خلال رحلة صيد. كنت أشعر بالإحراج حتى من التحدث معه، لكنه أقسم لي بفعاليتها. أفضل قرار اتخذته. سارة طرحت عليّ أسئلة مفصلة عن نمط حياتي وصحتي وحتى نظامي الغذائي. لم تكتفِ بوصف حبوب - بل وضعت خطة علاج فعلية. ما فاجأني أكثر هو المتابعة اللاحقة. إنها تتذكر محادثاتنا حقاً وتعدل الأشياء بناءً على وضعي.", date: "19/05/2025", effect: "نتائج كبيرة", usageTime: "3 أشهر مع سارة", featured: true },
    { id: 7, reviewerName: "طارق الناصر", age: "60", location: "جدة، السعودية", avatar: "https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=100&h=100&fit=crop&crop=face", rating: 5, content: "مطلق منذ 5 سنوات، وأخيراً قابلت امرأة مميزة. كان فك إخفاقها يُرعبني. كدتُ ألغي علاقتنا قبل أن تبدأ. كانت سارة متفهمة للغاية - لم تعاملني كرجل كبير بل كرجل يحتاج للمساعدة. كانت حذرة بشأن تاريخي الصحي، وتأكدت من سلامة قلبي قبل وصف أي شيء. في المرة الأولى مع سيدتي الجديدة... كل شيء عمل بشكل مثالي. نتحدث الآن عن الانتقال للعيش معاً. سارة منحتني فرصتي الثانية في الحب.", date: "02/06/2025", effect: "شفاء تام", usageTime: "4 أشهر مع سارة", featured: true },
    { id: 8, reviewerName: "سامي القحطاني", age: "55", location: "المنامة، البحرين", avatar: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=100&h=100&fit=crop&crop=face", rating: 5, content: "أعاني من السكري من النوع الثاني. كان قد قيل لي إن ضعف الانتصاب هو شيء يجب أن أتعايش معه. زوجتي تقبلت في الأساس أن هذا الجزء من زواجنا قد انتهى. سارة كانت مختلفة - سألت عن سكري وأدويتي، وحتى أرسلتني لفحص القلب قبل أن نبدأ. كانت حذرة وشاملة. والآن؟ دعنا نقول إن زوجتي سعيدة للغاية، وأنا أيضاً. سارة تفهم عملها حقاً وتكترث لسلامتك.", date: "14/06/2025", effect: "تحسن ملحوظ", usageTime: "3 أشهر مع سارة", featured: true },
    { id: 9, reviewerName: "فهد المطيري", age: "47", location: "أبوظبي، الإمارات", avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=100&h=100&fit=crop&crop=face", rating: 5, content: "20 عاماً من الزواج، وكان كل شيء قد أصبح روتينياً. ثم توقف كل شيء تماماً. كان الضغط يسحقني. سارة لم تحاول بيعني الأدوية الأغلى. بل أوصت بشيء ميسور التكلفة ومناسب لحالتي. بعد شهرين، أنا وزوجتي كأننا عرسان جدد. حتى أن سارة أعطتني نصائح حول الصحة العامة - النظام الغذائي، التمارين، إدارة التوتر. إنها تعالج الإنسان ككل.", date: "28/06/2025", effect: "شفاء تام", usageTime: "شهران مع سارة", featured: true },
    { id: 10, reviewerName: "ناصر الدوسري", age: "35", location: "الخبر، السعودية", avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&h=100&fit=crop&crop=face", rating: 5, content: "حياة العمل المكثفة دمرت صحتي - 80 ساعة أسبوعياً، توتر مستمر، نظام غذائي سيء. في 35، كانت رغبتي الجنسية كرجل في السبعين. خطيبتي كانت متفهمة، لكنني عرفت أن ذلك يدمر علاقتنا. وضعت سارة خطة عافية شاملة، وليست مجرد أدوية. تتابعني للتأكد من أنني أنام أفضل وأدير التوتر. التغيير كان لا يصدق - في الفراش وفي مستوى طاقتي في العمل. أروج لسارة لجميع أصدقائي المقاولين.", date: "11/07/2025", effect: "شفاء تام", usageTime: "3 أشهر مع سارة", featured: true },
    { id: 11, reviewerName: "ماجد الشمري", age: "43", location: "الدوحة، قطر", avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&h=100&fit=crop&crop=face", rating: 5, content: "أول مرة أستشير فيها عبر الإنترنت حول هذا الموضوع. كنت أشعر بالحرج الشديد وأتلعثم في كلماتي. جعلتني سارة أشعر بالراحة. لديها طريقة في التحدث عن كل شيء بموضوعية، بدون أحكام. شرحت لي توقيت الجرعات، ما يجب توقعه، وما يجب تجنبه. استخدمت توصياتها لمدة شهرين الآن، وكل مرة كانت ناجحة. عادت ثقتي بنفسي، وأنا أستمتع بالمواعدة مرة أخرى.", date: "24/07/2025", effect: "تحسن كبير", usageTime: "شهران مع سارة", featured: false },
    { id: 12, reviewerName: "بندر الحربي", age: "49", location: "المدينة المنورة", avatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=100&h=100&fit=crop&crop=face", rating: 5, content: "كنت قد جربت طلب أشياء عبر الإنترنت من قبل - مواقع مشبوهة، حبوب مشكوك فيها، نتائج متفاوتة. سارة كانت مختلفة تماماً. محترفة، مرخصة، تعرف حقاً ما تتحدث عنه. حولتني لدواء مختلف يعمل بشكل أفضل مع جسمي، وعدلت التوقيت، والآن كل شيء يسير على ما يرام في كل مرة. الفرق بين صيدلية إنترنت عشوائية وأخصائي طبي حقيقي هائل.", date: "05/08/2025", effect: "نتائج ممتازة", usageTime: "شهر مع سارة", featured: false },
    { id: 13, reviewerName: "راشد العتيبي", age: "40", location: "دبي، الإمارات", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face", rating: 5, content: "كانت خطيبتي تضايق من حياتنا الجنسية - أو انعدامها. كنت أتجنب الحميمية وأختلق أعذاراً بالتعب. الحقيقة كانت أنني لم أستطع الأداء ولم أعرف ماذا أفعل. كانت سارة مطمئنة. قالت إن هذا قابل للعلاج، وأعطتني خطة محددة. في المرة الأولى بعد بدء العلاج، استمررت 15 دقيقة. كانت خطيبتي مصدومة - بشكل إيجابي. علاقتنا أقوى من أي وقت مضى. سارة أنقذتنا حرفياً.", date: "18/08/2025", effect: "شفاء تام", usageTime: "شهران مع سارة", featured: true },
    { id: 14, reviewerName: "جاسم المالك", age: "58", location: "مسقط، عمان", avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100&h=100&fit=crop&crop=face", rating: 5, content: "ظننت أن حياتي الجنسية انتهت في هذا العمر. ابني هو الذي أقنعني بالتواصل مع سارة - كان قلقاً من أن أعيش وحيداً. شرحت لي سارة كيف يعمل الدواء، وأن العمر ليس الحاجز الذي ظننته. كانت محترمة، لم تجعلني أشعر بالعجز أو الإحراج. الآن أتواعد مرة أخرى، وأواكب نساء أصغر مني بعشر سنوات. يشعرني بالروعة استعادة هذا الجزء من حياتي. الشكر لسارة ولدفع ابني.", date: "01/09/2025", effect: "تحسن ملحوظ", usageTime: "4 أشهر مع سارة", featured: true },
    { id: 15, reviewerName: "حمدان الكetbi", age: "46", location: "الشارقة، الإمارات", avatar: "https://images.unsplash.com/photo-1542596594-649edbc13630?w=100&h=100&fit=crop&crop=face", rating: 5, content: "أنا سائق شاحنة، على الطريق باستمرار. الأدوية العادية كانت صعبة التوقيت مع جدولي المجنون. فهمت سارة نمط حياتي على الفور. أوصت بشيء يدوم لفترة أطول حتى لا أضطر لتخطيط كل شيء بدقة. يعمل بشكل مثالي مع جدولي غير المتوقع. حتى أنها ترسل لي رسائل تذكير عندما تعلم أنني في رحلة طويلة. هذا هو النوع من الاهتمام الشخصي الذي لا تتوقعه.", date: "14/09/2025", effect: "يعمل بشكل رائع", usageTime: "3 أشهر مع سارة", featured: false },
    { id: 16, reviewerName: "سلطان القاسمي", age: "37", location: "الرياض، السعودية", avatar: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=100&h=100&fit=crop&crop=face", rating: 5, content: "متزوج حديثاً وواجهت بالفعل مشاكل في غرفة النوم. كان الضغط مكثفاً - زوجة جديدة، توقعات، بالإضافة إلى قلقي. كانت سارة سريعة الاستجابة، وفهمت مدى إلحاحية وضعي. المرة الأولى باستخدام توصياتها كانت كأننا في شهر العسل مرة أخرى. بعد ستة أشهر، ما زلنا مستمرين بقوة. أنا أدين لسارة بأنها منحت زواجي البداية التي يستحقها.", date: "27/09/2025", effect: "شفاء تام", usageTime: "6 أشهر مع سارة", featured: true },
    { id: 17, reviewerName: "عبدالرحمن السبيعي", age: "51", location: "جدة، السعودية", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face", rating: 5, content: "ارتفاع ضغط الدم مع ضعف الانتصاب هو مزيج مخيف. كنت خائفاً من تجربة أي شيء بسبب قلبي. أخذت سارة الوقت لمراجعة جميع أدويتي، واستشارتني بشأن التوقيت والسلامة. كانت أكثر شمولاً من طبيبي الخاص. بعد ثلاثة أشهر، ضغط دمي مستقر وضعف الانتصاب تحت السيطرة. نسقت مع طبيب القلب لديّ للتأكد من أن كل شيء آمن. هذا هو الاحتراف الحقيقي.", date: "08/10/2025", effect: "تحسن ملحوظ", usageTime: "3 أشهر مع سارة", featured: false },
    { id: 18, reviewerName: "مشعل الدوسري", age: "44", location: "الكويت", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face", rating: 5, content: "زواجي الثاني، وكنت مرعوباً من إفساده. انتهى زواجي الأول جزئياً بسبب مشاكل حميمية لم أعالجها. لم أرد تكرار هذا النمط. أجرت سارة استشارة كاملة، و或صت بالضبط بما أحتاجه. زوجتي الجديدة لا تعلم أنني كنت أعاني من مشكلة - تظن أنني على طبيعتي. سرية سارة وفعاليتها منحتني بداية جديدة.", date: "22/10/2025", effect: "شفاء تام", usageTime: "شهران مع سارة", featured: true },
    { id: 19, reviewerName: "تركي الحميد", age: "41", location: "القاهرة، مصر", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face", rating: 5, content: "كنت قد جربت حبوباً من قبل، مكملات غذائية، حتى تلك العلاجات المشبوهة عبر الإنترنت. لم يعمل شيء. كنت على استعداد للاستسلام وأتقبل أن هذه هي حياتي الآن. سارة كانت محاولتي الأخيرة. شرحت لي لماذا فشلت تلك الأشياء الأخرى وكيف يختلف نهجها. كانت على حق. لأول مرة منذ سنوات، كل شيء يعمل كما يجب. أقول لكل رجل أعرفه يعاني - اتصل بسارة.", date: "04/11/2025", effect: "شفاء تام", usageTime: "4 أشهر مع سارة", featured: true },
    { id: 20, reviewerName: "فيصل النوفل", age: "56", location: "دبي، الإمارات", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face", rating: 5, content: "تركتني جراحة البروستاتا في 54 مع ضعف انتصاب. قال لي أخصائي المسالك إنه قد يتحسن وقد لا يتحسن. لم يتحسن. كنت مكتئباً، أشعر أنني نصف رجل. تواصلت سارة مع جراحي لفهم وضعي المحدد، ثم وضعت خطة علاج حذرة وتدريجية. بدأنا بجرعة منخفضة وبطيئة. الآن، بعد عامين من الجراحة، أنا وزوجتي حميمان مرة أخرى. إنه مختلف عما قبل، لكنه جيد. سارة لم تستسلم لي حين كنت على استعداد للاستسلام لنفسي.", date: "17/11/2025", effect: "تحسن ملحوظ", usageTime: "5 أشهر مع سارة", featured: true }
];

// Stats
const enStats = { totalReviews: '10000+', verifiedClients: '10000+', successRate: 99 };
const arStats = { totalReviews: '+10000', verifiedClients: '+10000', successRate: 99 };

// Data Manager
const DataManager = {
    getReviews(lang = 'en') {
        return lang === 'ar' ? arReviews : enReviews;
    },

    getFeaturedReviews(limit = 40, lang = 'en') {
        const reviews = lang === 'ar' ? arReviews : enReviews;
        return reviews.filter(r => r.featured).slice(0, limit);
    },

    getStats(lang = 'en') {
        return lang === 'ar' ? arStats : enStats;
    },

    initData() {
        console.log('Data initialized');
    }
};
